server:
    port: 9400

spring:
    cloud:
        consul:
            host: localhost
            port: 8500
            discovery:
                instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
                healthCheckInterval: 15s
